name: Test

on:
  push:
    branches: [ "main" ]

jobs:
  unit-test:
    name: Run Tests
    env:
      SECRET_CONNEXION: ${{ secrets.SECRET_CONNEXION }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node]v1
        with:
          node-version: "21"
      - run: npm install
      - run: npm run test
